void   winopen(U16 w, U16 h, const char *title, U16 fps);
void   winclose(void);
Image* frame(void);
void   flush(void);
U64    lastframetime(void);
OK     keyisdown(U8 k);
OK     keywaspressed(U8 k);
OK     btnisdown(U8 b);
OK     btnwaspressed(U8 b);
void   mouselock(OK on);
I      mousex(void);
I      mousey(void);
