void   winopen(U16 w, U16 h, const char *title, U16 fps);
void   winclose(void);
Image* framebegin(void);
void   frameend(void);
void   flush(void);
U64    lastframetime(void);
int    keyisdown(U8 k);
int    keywaspressed(U8 k);
int    btnisdown(U8 b);
int    btnwaspressed(U8 b);
void   mouselock(int on);
int    mousex(void);
int    mousey(void);
